const locations = [
{ route: "Central Spokane", placeId: "ChIJP29QyeUYnlQR7NclQlFHvSg", edition: "EWA", notes: "Inside Auto Clipper Rack" },
{ route: "Central Spokane", placeId: "ChIJOVp3KOQYnlQRZt78rofalF0", edition: "EWA", notes: "Shared rack top shelf; 6pm close" },
{ route: "Central Spokane", placeId: "ChIJaxHCMOEYnlQRq0Lk3Bl0HuI", edition: "EWA", notes: "Shared rack inside" },
{ route: "Central Spokane", placeId: "ChIJffVkJN4YnlQRueeV7BzxHxo", edition: "EWA", notes: "Inlander store rack - 2 pockets, west door." },
{ route: "Central Spokane", placeId: "ChIJBfQ0CyMZnlQRCnVtXnLZ4f8", edition: "EWA", notes: "Inlander Rack; Opens at 12pm" },
{ route: "Central Spokane", placeId: "ChIJpWcTcCMZnlQRVmhLkeaxSWM", edition: "EWA", notes: "Inside Store Rack" },
{ route: "Central Spokane", placeId: "ChIJpetyQTsZnlQR-ODvgpN1x5Y", edition: "EWA", notes: "Community rack - claim top shelf" },
{ route: "Central Spokane", placeId: "ChIJc8NVBzsZnlQR2KJkBZQQdzE", edition: "EWA", notes: "Single EX rack inside" },
{ route: "Central Spokane", placeId: "ChIJJeDyJzQZnlQRa91quEi_bqc", edition: "EWA" },
{ route: "Central Spokane", placeId: "ChIJZwb96TkZnlQRrkOTLBWjZlQ", edition: "EWA", notes: "Inlander Rack" },
{ route: "Central Spokane", placeId: "ChIJPa0txDcZnlQRpMu5PY1AT1w", edition: "EWA", notes: "Table in entryway" },
{ route: "Central Spokane", placeId: "ChIJTTklM-CBVIcR7sFsTCIsoYc", edition: "EWA", notes: "Inlander Rack" },
{ route: "Central Spokane", placeId: "ChIJqSnPJ0gZnlQRFgi53PzUYCA", edition: "EWA", notes: "Inlander Rack" },
{ route: "Central Spokane", placeId: "ChIJl_Rar0kZnlQRIXfWd2Euf0I", edition: "EWA", notes: "Inside Community Shelf" },
{ route: "Central Spokane", placeId: "ChIJXdkuFkoZnlQR5TXI5S7znhY", edition: "EWA" },
{ route: "Central Spokane", placeId: "ChIJeYSyuUsZnlQRNVwTYeHjHII", edition: "EWA", notes: "Single EX rack inside main entrance" },
{ route: "Central Spokane", placeId: "ChIJUQsZmocYnlQRkesb_WBdpTI", edition: "EWA", notes: "(at HF Hospital, NE Corner of building)Single EX rack by fireplace" },
{ route: "Central Spokane", placeId: "ChIJh-pSuEsZnlQR7ujQJphXnv4", edition: "EWA", notes: "Double EX rack inside" },
{ route: "Central Spokane", placeId: "ChIJPZzyvEwZnlQRmnWaRJbyqlA", edition: "EWA", notes: "Inside EX Rack" },
{ route: "Central Spokane", placeId: "ChIJoZ9PI00ZnlQR_ciucHcGvyI", edition: "EWA", notes: "Inlander Rack" },
{ route: "Central Spokane", placeId: "ChIJy_oF37MenlQRvOceQQPIX9o", edition: "EWA", notes: "Inside EX Rack;" },
{ route: "Central Spokane", placeId: "ChIJF2oDkbIenlQRG5DmxnvJtTM", edition: "EWA" },
{ route: "Central Spokane", placeId: "ChIJL0Bd27IenlQR4CuK1-2dxAA", edition: "EWA", notes: "Inside EX wire rack" },
{ route: "Central Spokane", placeId: "ChIJ3Vrj6CEZnlQRF5RcrU00CtE", edition: "EWA", notes: "Single EX rack ;" },
{ route: "Central Spokane", placeId: "ChIJDylrhO8YnlQR5_Ixr4GefRg", edition: "EWA" },
{ route: "Central Spokane", placeId: "ChIJ12Ihku8YnlQROBq0xvoixP8", edition: "EWA", notes: "Inside EX Rack" },
{ route: "Central Spokane", placeId: "ChIJeVF6le8YnlQRhNZAzwKpsns", edition: "EWA", notes: "Inlander Rack" },
{ route: "Central Spokane", placeId: "ChIJ28lDRPEYnlQR9_uolwbP9DA", edition: "EWA" },
{ route: "Central Spokane", placeId: "ChIJ37N-Hu4YnlQRTxsRCtKmdQk", edition: "EWA", notes: "Need Rack?" },
{ route: "Central Spokane", placeId: "ChIJf8VdM8wZnlQRb19r2K_AJVU", edition: "EWA", notes: "Inlander Rack" },
{ route: "Colville Loop", placeId: "ChIJQecdvov9YVMRSd1dQnH5B24", edition: "EWA", notes: "Single EX outside" },
{ route: "Colville Loop", placeId: "ChIJmW1VYYEHYlMR6-JMRL7L81E", edition: "EWA", notes: "Inside Single EX Rack" },
{ route: "Colville Loop", placeId: "ChIJ__-LFIEHYlMRTzG4wwROmb0", edition: "EWA", notes: "Inside Single EX Rack" },
{ route: "Colville Loop", placeId: "ChIJN9xnEIEHYlMRk06Ed2L0zNE", edition: "EWA, IND", notes: "Outside Double EX; 1 BUNDLE OF INLANDER; <-- Please write returns here" },
{ route: "Colville Loop", placeId: "ChIJWWkevxMKYlMRROEENAnzOOU", edition: "EWA", notes: "Leave on Bench if closed; Inside white community" },
{ route: "Colville Loop", placeId: "ChIJ3yQ34zULYlMRqXLbeY7gK-g", edition: "EWA", notes: "Community Rack Right, by Deli" },
{ route: "Colville Loop", placeId: "ChIJ54b2ep50YlMR4D8z6cWh4ro", edition: "EWA, IND", notes: "Outside Tall Angle Iron; 1 BUNDLE OF INLANDER; <-- Please write returns here" },
{ route: "Colville Loop", placeId: "ChIJG4zwhH9zYlMRMRAVB3n9IVM", edition: "EWA", notes: "Bag" },
{ route: "Colville Loop", placeId: "ChIJN9gANNRzYlMRi2iqZlrxxsc", edition: "EWA" },
{ route: "Colville Loop", placeId: "ChIJw5Uh-WJzYlMRTuWbQcZW848", edition: "EWA, IND", notes: "Inander Rack, Opens at 10AM, BAG IF CLOSED; 1 BUNDLE OF INLANDER" },
{ route: "Colville Loop", placeId: "ChIJt7gbTH1zYlMRSRiO_OBGDB8", edition: "EWA, IND", notes: "4 pockets + Bottom Shelf Inlander Rack; 3 1/2 BUNDLE OF INLANDER; <-- Please write returns here" },
{ route: "Colville Loop", placeId: "ChIJ_ZLGH31zYlMRBuftumZJdQc", edition: "EWA", notes: "Inside EX Single" },
{ route: "Colville Loop", placeId: "ChIJ7XJz94h2YlMR0bXb99yTy2U", edition: "EWA", notes: "Shelf above EPOCH" },
{ route: "Colville Loop", placeId: "ChIJfQOAVK57YlMR4yJubXbDN4A", edition: "EWA", notes: "INSIDE COUNTER" },
{ route: "Colville Loop", placeId: "ChIJ72WeAQ18YlMRQcAMitWpCuI", edition: "EWA", notes: "Outside EX Double Rack" },
{ route: "Colville Loop", placeId: "ChIJcYzHgnB9YlMR7iE4YqLJE3g", edition: "EWA", notes: "Inside Shared rack" },
{ route: "Colville Loop", placeId: "ChIJma3Hn3t9YlMR4Nvn0WHySag", edition: "EWA" },
{ route: "Colville Loop", placeId: "ChIJ_YvqbXt9YlMRbOQjj4vdFv8", edition: "EWA", notes: "Inside EX Rack" },
{ route: "Colville Loop", placeId: "ChIJJTR-aHt9YlMR9lyhglOwhKw", edition: "EWA", notes: "Two outside racks - one on either side; Most papers on South door" },
{ route: "Colville Loop", placeId: "ChIJS9Co0nx9YlMRrK_OEVThYx4", edition: "EWA", notes: "Inside second doors, to left on shelf" },
{ route: "Colville Loop", placeId: "ChIJPw1rJoaHYlMR436R97YBvx8", edition: "EWA", notes: "Inside Community Rack Center of store" },
{ route: "Colville Loop", placeId: "ChIJDzECvo6HYlMRZYYUiL55O3s", edition: "EWA", notes: "Outside EX Double" },
{ route: "Colville Loop", placeId: "ChIJK5l65Y6HYlMRvqUVw2WWE0A", edition: "EWA", notes: "Inside Community rack by Check Stand" },
{ route: "Colville Loop", placeId: "ChIJxyy25I6HYlMRNpju8aRDPYM", edition: "EWA", notes: "USE inside White Sasquatch rack" },
{ route: "Colville Loop", placeId: "ChIJvbfY04-HYlMRjPl4GAUoke0", edition: "EWA", notes: "Inside Rack" },
{ route: "Colville Loop", placeId: "ChIJXbDBUImHYlMRwxjnPmbEtWY", edition: "EWA, IND" },
{ route: "Colville Loop", placeId: "ChIJqXXLS5eHYlMR5HuQB-QPHAo", edition: "EWA, IND", notes: "20 bundles at 40 dependent on page count Inlanders on bottom rack Leave only 1 pocket for N.Colombia" },
{ route: "Colville Loop", placeId: "ChIJyw0BSQ2EYlMRhTm7Ht3H2uE", edition: "EWA", notes: "Bottom Shelf in from door; Inside Rack" },
{ route: "Colville Loop", placeId: "ChIJKZAfTwyEYlMRDlV8FArG4Qs", edition: "EWA", notes: "Drop in book drop box" },
{ route: "Colville Loop", placeId: "ChIJh2sQK3OEYlMR4Gyz9BR4JNU", edition: "EWA", notes: "Leave in Laundry - Other end of building" },
{ route: "Colville Loop", placeId: "ChIJpYVletPqnVQR2Jualchhifc", edition: "EWA", notes: "YELLOW RACK" },
{ route: "Colville Loop", placeId: "ChIJe8hUQ57EnVQRPbWtS88lbwM", edition: "EWA", notes: "Outside single EX" },
{ route: "Colville Loop", placeId: "ChIJr7HJOZLgnVQRGXwjZ50mDS0", edition: "EWA", notes: "Store Rack" },
{ route: "Colville Loop", placeId: "ChIJi2Gz8g3hnVQR1tCcJWcgxwo", edition: "EWA", notes: "INSIDE single EX" },
{ route: "Colville Loop", placeId: "ChIJD-2O0bPjnVQREX2l-WUbsBM", edition: "EWA", notes: "INSIDE double EX" },
{ route: "Colville Loop", placeId: "ChIJyfETOavjnVQRBgH_pASEeRs", edition: "EWA", notes: "Only wants 10 papers" },
{ route: "Colville Loop", placeId: "ChIJpb0KuPkEnlQRiZVZFnj-Z6M", edition: "EWA", notes: "Inlander Community Rack; 3 Pockets" },
{ route: "Colville Loop", placeId: "ChIJ77N6vPkEnlQROS2MrIPTJwA", edition: "EWA", notes: "Inside Single Ex;" },
{ route: "Colville Loop", placeId: "ChIJ_w1fCNEanlQR7X0YzoxLqsM", edition: "EWA", notes: "Green Community Box Top Right spot" },
{ route: "Colville Loop", placeId: "ChIJgycTCNEanlQRhh2F9pMnbnk", edition: "EWA", notes: "Outside EX Single;" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJM0RElicfnlQR7vlQMSJjQGE", edition: "EWA", notes: "Inlander Store Rack Rack - 2 pockets; North Door (MAX 120 for 30)" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJq6raq94enlQR6CKdnv4HAL0", edition: "EWA", notes: "Black Spokesman Rack inside door" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJbc-jMN0enlQRqptZMsDr9sI", edition: "EWA", notes: "Inside top pocket of rack" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJZ3rf6ukenlQRKAAnnkdF7eg", edition: "EWA", notes: "Single EX rack" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJO4LlDYQenlQRQq05g33ndM0", edition: "EWA", notes: "; RED EX (old Auto Clipper) Box" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJg_ZE0r8dnlQRn_tvUEP7iV8", edition: "EWA", notes: "Shared rack, top shelf inside" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJWxAiipYdnlQRmGHy5WBw9aY", edition: "EWA", notes: "Leave by entrance door, bag if possible" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJ2XSZzHgdnlQRQhIS_6Yp7QA", edition: "EWA", notes: "Inlander Community Rack; 3 Pockets ;" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJeyuYtH0dnlQRoSMncn2vRQo", edition: "EWA", notes: "Yellow Community Rack, Right of dooe outside (MAX 60)" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJdzDes4LiYVMRh_Cw4U05MdI", edition: "EWA", notes: "OUTSIDE RED BOX" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJSXfu2sriYVMRDmoqtDOJUJc", edition: "EWA", notes: "Bag - Opens at 11am" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJwZB1Tqj-YVMRCUQ5c8YwMpU", edition: "EWA", notes: "EX Single Wire Rack w/ WCD;" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJT9JLlu74YVMRnx_7wbrcP3A", edition: "EWA", notes: "Inside store Rack (MAX 120 for bundles of 30)" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJ-4uYp5MCYlMRpSMN83Pzdxg", edition: "EWA", notes: "Outside Double Ex Wire Rack" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJTzgtKHP_YVMR8b0w0NAi5h4", edition: "EWA", notes: "EX Single Wire Rack Inside" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJqdtthZ7_YVMRBZfE6PhPZXs", edition: "EWA", notes: "@ Roundabout Store Rack" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJIRIEGpL_YVMRI2ZJIZakJII", edition: "EWA", notes: "Inside Community Shelf" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJvZoZcJL_YVMRSp7SnVSqxlA", edition: "EWA", notes: "; On Pillar By Window" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJa8JfnI7_YVMR4B9tXR4hGkA", edition: "EWA", notes: "Angle Iron Exchange Rack" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJHXB2EY3_YVMRoXFjjOAkn6A", edition: "EWA", notes: "Opens 11 AM Bottom of Huckleberry rack" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJbWdMjI3_YVMRnOHCUZl29k8", edition: "EWA", notes: "Spread across Tables, counters, rack" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJq3o6exb_YVMRVKRx7vGu1AM", edition: "EWA" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJ2UPJ8ZL_YVMRykdWEOhY4kk", edition: "EWA", notes: "Desk" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJbSOxZJL_YVMRUYDirSp5rvs", edition: "EWA", notes: "Store shelves" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJ_dp_SZP_YVMRa6rF4wf_4hA", edition: "EWA", notes: "Coffee Table" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJz14fHvT_YVMRwSUGB8AxCSY", edition: "EWA" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJr0N8mOv_YVMRJ4dzCNqvvkk", edition: "EWA", notes: "EX Single Wire Rack Opens 11AM (side door if not open)" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJDdwoejP_YVMRWVW1zczpiMU", edition: "EWA", notes: "Bottom of Huckleberry rack" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJmTiRVer_YVMRdLc58oGiMJk", edition: "EWA", notes: "Inlander Community Rack; 4 Pockets" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJ0QRdYur_YVMRBuSAvgjt-78", edition: "EWA", notes: "EX Single Angle Iron Rack; Inside North Door" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJD4H9XFH_YVMRE0s376omEOI", edition: "EWA", notes: "2 Racks inside by door to Left wooden" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJWYzbier_YVMRgay1MAYFbgs", edition: "EWA", notes: "Inside EX Single Wire Rack (MAX 75 bundles of 30)" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJjYHA6ur_YVMR6HvLB_oVBgc", edition: "EWA", notes: "Single wire EX rack" },
{ route: "Deer Park/ Spokane North", placeId: "ChIJIUoY-ev5YVMRtQdwjwJcl7o", edition: "EWA", notes: "opens 11, leave bag; Entry shelf" },
{ route: "Downtown Spokane", placeId: "ChIJt6AIjqgYnlQR39Sk8EpS-as", edition: "EWA", notes: "opens 9:30am" },
{ route: "Downtown Spokane", placeId: "ChIJ16T1W6IYnlQRN7KKBV4ahIM", edition: "EWA", notes: "Tall Single EX Rack               opens 10am" },
{ route: "Downtown Spokane", placeId: "ChIJo5MfxpMYnlQRsX8kCDfwKI0", edition: "EWA", notes: "Single EX Wire rack at front counter" },
{ route: "Downtown Spokane", placeId: "ChIJZZmrmGYYnlQRpzAD3cplP18", edition: "EWA", notes: "Community rack to right" },
{ route: "Downtown Spokane", placeId: "ChIJ6_HqxLsYnlQRZ9DhWjPn9hA", edition: "EWA", notes: "Single EX outside" },
{ route: "Downtown Spokane", placeId: "ChIJsZ3hvWkYnlQR87Y1Las77VY", edition: "EWA" },
{ route: "Downtown Spokane", placeId: "ChIJiZdEimkYnlQRT_exGUsyGFU", edition: "EWA", notes: "Inlander Community Rack; 1 Pocket 1 Shelf; North Door" },
{ route: "Downtown Spokane", placeId: "ChIJCWjZUGoYnlQRWqWivowTAe0", edition: "EWA" },
{ route: "Downtown Spokane", placeId: "ChIJw2O_TVkYnlQRTC9432RSkfE", edition: "EWA", notes: "Share Inlander rack" },
{ route: "Downtown Spokane", placeId: "ChIJ6ZBH714YnlQR5Y8O3VhBjio", edition: "EWA" },
{ route: "Downtown Spokane", placeId: "ChIJNza6-GEYnlQRPKhRwhlCTOI", edition: "EWA", notes: "Inside building to the right; Green Leaflet Rack" },
{ route: "Downtown Spokane", placeId: "ChIJtb_puWEYnlQRjXxo-ZujY4A", edition: "EWA", notes: "Inside White Exchange Rack in Foyer" },
{ route: "Downtown Spokane", placeId: "ChIJ7UZX2mAYnlQR6rPsMglY7q4", edition: "EWA", notes: "Inlander Rack" },
{ route: "Downtown Spokane", placeId: "ChIJBzQ9G14YnlQRcH7bm3zE3Dw", edition: "EWA", notes: "Single EX 2 shelf rack South entrance near juice bar/ self check out" },
{ route: "Downtown Spokane", placeId: "ChIJrUu6EmkYnlQRsC9rTuzLkn8", edition: "EWA", notes: "Outside EX Single Rack" },
{ route: "Downtown Spokane", placeId: "ChIJVc8TyHEYnlQRRivLkNtuoLk", edition: "EWA", notes: "Inside EX rack; Angle Iron Community; shared with Inlander" },
{ route: "Downtown Spokane", placeId: "ChIJjdIaunYYnlQR91CUVZAuCss", edition: "EWA", notes: "Inlander Store Rack; 1 Pocket" },
{ route: "Downtown Spokane", placeId: "ChIJt7SzOWQYnlQRREitJyFCGM0", edition: "EWA", notes: "Inside EX Rack" },
{ route: "Downtown Spokane", placeId: "ChIJkT0_1WUYnlQRxAt_EKL5VH4", edition: "EWA", notes: "Inside EX Single Rack" },
{ route: "Downtown Spokane", placeId: "ChIJ99brF4gYnlQRjaxose4Lv2U", edition: "EWA", notes: "Max 3 bundles; Stacks on counter" },
{ route: "Downtown Spokane", placeId: "ChIJGUnmEIgYnlQRMaK8sThThNs", edition: "EWA", notes: "Inside Exchange Rack" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJVW8IagQ-nlQRGzEHvHRdZv4", edition: "EWA", notes: "outside front door" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJp9IL81MVnlQRq376nCPRNt4", edition: "EWA", notes: "Outside store rack" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJfTSOzqtqnlQRZVClzInEcoc", edition: "EWA", notes: "1 long pocket, 1 shelf" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJKRZSdMg4nlQRaQWlDcjM4gU", edition: "EWA", notes: "Inlander Community Rack; 1 pocket (Right entrance)" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJGazQxcc4nlQRdulfSEzjUsQ", edition: "EWA", notes: "Rack inside door on left" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJeaQQn7g4nlQRRhIHM5jf2dE", edition: "EWA", notes: "Inside front door" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJT5qEpLg4nlQRArTCHxYP1Wk", edition: "EWA", notes: "Inside front door" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJy4ZtNr84nlQRRwAs51Uk3vE", edition: "EWA", notes: "On far left counter" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJswLpvJc4nlQRHpcfA6GL7LM", edition: "EWA", notes: "Outside" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJqcykf2JHnlQRb8ebq97Ciy8", edition: "EWA" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJ2TC_Y2JHnlQR6Q-RuhxyEyc", edition: "EWA", notes: "Inside on Inlander rack;" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJkUdxmZk4nlQRbieBwzxDDaQ", edition: "EWA", notes: "Inside ;" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJYcZGRZk4nlQRipJcL7r4WKs", edition: "EWA", notes: "On the bench inside" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJqx4r25k4nlQRoHMp2M92Yoo", edition: "EWA", notes: "Single EX rack East entrance" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJ09oFDr84nlQRYzVkydkVyWU", edition: "EWA", notes: "Leave in waiting area" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJI2UMZ784nlQRgaTy1etkj-Q", edition: "EWA", notes: "North Door; Exchange Rack and Inlander Community Rack 1 Pocket" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJU5ff7GE5nlQRiR5N8cBrkx4", edition: "EWA", notes: "Inside entryway, single EX single shelf MAX 60" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJ896wo8g4nlQRx15O92vgI-U", edition: "EWA", notes: "Window Counter" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJA1CWVE0-nlQRi6-_NjR_CfU", edition: "EWA", notes: "Single EX rack ; Inlander on bottom;" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJGdtozwg-nlQRyjgcmieB--A", edition: "EWA", notes: "Use front truck rack, inside first door on left" },
{ route: "Medical Lake/ Cheney", placeId: "ChIJkcGOitUXnlQRE6e0ZgaRwEE", edition: "EWA", notes: "Bottom of Spokesman rack at front door" },
{ route: "Moses Lake", placeId: "ChIJuf0HFCo5mVQR_Haft1ej-eA", edition: "IND", notes: "Take Exit 179; 1/2 Bundle of Inlander" },
{ route: "Moses Lake", placeId: "ChIJO_ABvrw4mVQRDzkhBcs64CY", edition: "EWA, IND", notes: "Inside Rack Far Left or Northern Entrance; 1 Bundle of Inlander" },
{ route: "Moses Lake", placeId: "ChIJgx1-Bl5HmVQRXRCeWfeM3Zg", edition: "EWA, IND", notes: "Rack Inside Right Main Door leave WML Copies primary; 1/2 Bundle of Inlander" },
{ route: "Moses Lake", placeId: "ChIJUXK5FRQ_mVQR7UNxVcWHd4Y", edition: "EWA, IND", notes: "Inside Rack On top/Inlander on bottom; 2 blocks past is 1-90 On Ramp; 1 Bundle of Inlander" },
{ route: "Newport/ North Idaho", placeId: "ChIJ65UXOH_dYVMRrwtVWjZEpf0", edition: "EWA", notes: "Outside community rack; w/ rock" },
{ route: "Newport/ North Idaho", placeId: "ChIJ53bzOCbqYVMRz0IE8VB6bvg", edition: "NID", notes: "Inside Table" },
{ route: "Newport/ North Idaho", placeId: "ChIJ1QoWMwDrYVMRybzsal_Q0Bw", edition: "NID", notes: "Place on ground by entry door." },
{ route: "Newport/ North Idaho", placeId: "ChIJASaxL43rYVMR3ivcwBn0mn4", edition: "NID", notes: "Set both Giorgis and O'Malleys on bench inside door" },
{ route: "Newport/ North Idaho", placeId: "ChIJlQeFhQfrYVMRmlu-xSt3sXw", edition: "NID", notes: "Inside Window Sill; OPENS 6AM" },
{ route: "Newport/ North Idaho", placeId: "ChIJmxC5iPzqYVMRqeKE9Ol8Am8", edition: "NID", notes: "Set on ground by entry door if not open" },
{ route: "Newport/ North Idaho", placeId: "ChIJE9woaQLrYVMR3YMGZcKazTQ", edition: "NID", notes: "Outside EX Angle Iron Rack NEEDS PAINTED" },
{ route: "Newport/ North Idaho", placeId: "ChIJ5yTz8X2VYVMR0K96tdN4G98", edition: "NID", notes: "On counter" },
{ route: "Newport/ North Idaho", placeId: "ChIJJfluIeyNYVMRCcFbxPwsyk8", edition: "NID", notes: "EX SINGLE RACK Inside store" },
{ route: "Newport/ North Idaho", placeId: "ChIJRwgb6ZKNYVMRxsOITOvnwJk", edition: "NID", notes: "Outside" },
{ route: "Newport/ North Idaho", placeId: "ChIJbe2F8pKNYVMRe8ggB7L8kfY", edition: "NID", notes: "Inside Table" },
{ route: "Newport/ North Idaho", placeId: "ChIJz9tO7pKNYVMRS0i3gWEG33I", edition: "NID", notes: "Inside Single ; EX Rack; Right of door" },
{ route: "Newport/ North Idaho", placeId: "ChIJffHmIpONYVMRSj3fzW_upmg", edition: "NID", notes: "Outside EX Single Rack; w/ WCD" },
{ route: "Newport/ North Idaho", placeId: "ChIJ2ZaTYpONYVMRrsVpaS-5Z_Y", edition: "NID", notes: "Place by entry door" },
{ route: "Newport/ North Idaho", placeId: "ChIJFSVGp4mQYVMRqOFd29FD9oQ", edition: "NID", notes: "Outside White EX Rack" },
{ route: "Newport/ North Idaho", placeId: "ChIJzQqCq-mRYVMR2LC9XYHHZRA", edition: "NID", notes: "Outside white EX rack behind pillar at front door" },
{ route: "Newport/ North Idaho", placeId: "ChIJRfic_HeQYVMRaLDzzToghYg", edition: "NID", notes: "Inlander Community Rack ; 3 Pockets" },
{ route: "Newport/ North Idaho", placeId: "ChIJr7_3Qe3VY1MRx9YywQAAam8", edition: "NID", notes: "Outside Auto Clipper Rack; West side of building; w/ WCD" },
{ route: "Newport/ North Idaho", placeId: "ChIJq2E_5kgrYlMRgLabL0yX1tU", edition: "NID", notes: "Place on ground under NW rack" },
{ route: "Newport/ North Idaho", placeId: "ChIJRY5XTgApYlMRJWqafCO6blw", edition: "NID", notes: "Inside counter" },
{ route: "Newport/ North Idaho", placeId: "ChIJadh37RwmYlMRr8xaLj--nMc", edition: "NID", notes: "Inside Community Shelf; to the left of NW" },
{ route: "Newport/ North Idaho", placeId: "ChIJI7gIWQUmYlMRYwq05cb5it4", edition: "NID", notes: "Inside Community Rack" },
{ route: "Newport/ North Idaho", placeId: "ChIJfUNwPRsmYlMRHzsrVfk_tbE", edition: "NID", notes: "Single EX Wire rack" },
{ route: "Newport/ North Idaho", placeId: "ChIJFwv69DskYlMRbwBVJSkol9s", edition: "NID", notes: "Inside Community Rack" },
{ route: "Newport/ North Idaho", placeId: "ChIJqwokE3IlYlMRolWTC-oOeb8", edition: "NID", notes: "Inlander Community Rack; 3 Pockets" },
{ route: "Newport/ North Idaho", placeId: "ChIJc9DTKxUkYlMRBEmZ-JH7n_8", edition: "NID", notes: "Inside Foyer; EX Double Rack" },
{ route: "Newport/ North Idaho", placeId: "ChIJVzFz2mokYlMR64UwTS6vgr8", edition: "NID", notes: "On Front Counter" },
{ route: "Newport/ North Idaho", placeId: "ChIJkbCazRQkYlMRcTXsUb3b_j0", edition: "NID", notes: "Inside EX Single Rack" },
{ route: "Newport/ North Idaho", placeId: "ChIJ6UkIvhIkYlMRLVF1bLP7dEw", edition: "NID", notes: "Outside rack" },
{ route: "Newport/ North Idaho", placeId: "ChIJG3RAqBIkYlMRxGmG0AGyGjY", edition: "NID, EWA", notes: "Community Rack to Left of counter" },
{ route: "Newport/ North Idaho", placeId: "ChIJjXcGUg0kYlMRV77PA4h3LWo", edition: "EWA", notes: "Keokee Community Rack; 3 Pockets; 2nd, 3rd, 4th row on left" },
{ route: "Newport/ North Idaho", placeId: "ChIJ9X9lMnMkYlMRpWwYof9gNYI", edition: "EWA", notes: "inside entry way" },
{ route: "Newport/ North Idaho", placeId: "ChIJHWEsTQQiYlMRJZLPRUMBcBE", edition: "EWA", notes: "Outside EX Single Rack" },
{ route: "Newport/ North Idaho", placeId: "ChIJLfK9H3jfuVIRHWxnfhbnUYk", edition: "EWA", notes: "On top of trash can HOLD AT 5 PER OWNER; West Door" },
{ route: "Newport/ North Idaho", placeId: "ChIJlwBxx-0jYlMRdQ7XxTkjjUU", edition: "EWA", notes: "Inside EX Single Rack" },
{ route: "Newport/ North Idaho", placeId: "ChIJT51UK_gZYlMRaUomYdykgu8", edition: "EWA", notes: "on counter just inside door" },
{ route: "Newport/ North Idaho", placeId: "ChIJQW3WRtUeYlMRTLhQxgcSel4", edition: "EWA", notes: "Inside community rack; Top Shelf" },
{ route: "Newport/ North Idaho", placeId: "", edition: "NID, " },
{ route: "Northeast Spokane", placeId: "ChIJT9q84xTfYVMR38-YLXT5duA", edition: "EWA", notes: "Exchange rack in entrance" },
{ route: "Northeast Spokane", placeId: "ChIJb45qW_vfYVMRcpChHviwjIY", edition: "EWA", notes: "Inlander Community Rack; 1 Pocket - 60 Max" },
{ route: "Northeast Spokane", placeId: "ChIJ0-wp_47eYVMRiUa8uIMZAiI", edition: "EWA", notes: "Inside Exchange Rack" },
{ route: "Northeast Spokane", placeId: "ChIJg3OC4I7eYVMRePkSgEcWR6M", edition: "EWA", notes: "Second Shelf Community Rack" },
{ route: "Northeast Spokane", placeId: "ChIJ7bNBkYneYVMRC_-61Jm49hI", edition: "EWA", notes: "Inside Top Community Rack" },
{ route: "Northeast Spokane", placeId: "ChIJDSuMrr_fYVMRuUYaNc3Zfbo", edition: "EWA", notes: "Inside EX Rack" },
{ route: "Northeast Spokane", placeId: "ChIJE5APEnXgYVMRTQy-_1ZRkBU", edition: "EWA", notes: "inside comm rack" },
{ route: "Northeast Spokane", placeId: "ChIJk_cb6wvgYVMR5uA-ocmhLHg", edition: "EWA", notes: "Top of Community Rack" },
{ route: "Northeast Spokane", placeId: "ChIJm_agXQngYVMR93eP1biVdWY", edition: "EWA", notes: "inside EX rack; West Door" },
{ route: "Northeast Spokane", placeId: "ChIJuZoiPoYfnlQRaCbEiEgqf4o", edition: "EWA", notes: "Single EX Wire Rack; South Door" },
{ route: "Northeast Spokane", placeId: "ChIJkbeKSH0fnlQRsC-iQjPUGL8", edition: "EWA", notes: "EX Rack Inside Rt of Door; Parris - Manager" },
{ route: "Northeast Spokane", placeId: "ChIJI-2bdSkgnlQRBaskgw74vBc", edition: "EWA", notes: "Opens 11am; In Foyer Community Shelf" },
{ route: "Northeast Spokane", placeId: "ChIJUzdmLYYfnlQRGW2Pf6qQP3g", edition: "EWA", notes: "Inside EX Single Rack; South Door;" },
{ route: "Northeast Spokane", placeId: "ChIJIw3x7IgfnlQRocWhexcPFjE", edition: "EWA", notes: "Inlander Store Rack; 2 Pockets. (MAX 100 bundles 30)" },
{ route: "Northeast Spokane", placeId: "ChIJvTJIJ-cfnlQRLXBpyH7eLl0", edition: "EWA", notes: "Inside Community Angle Iron EX Rack" },
{ route: "Northeast Spokane", placeId: "ChIJRf5nF48fnlQRCyMqR066TMo", edition: "EWA", notes: "Opens 8am; store Spokesman rack" },
{ route: "Northeast Spokane", placeId: "ChIJ9aoHG8AfnlQRPmiN-ReXmXU", edition: "EWA", notes: "Inside EX Single Rack" },
{ route: "Northeast Spokane", placeId: "ChIJz80kgoUfnlQRyWDbt65zGRc", edition: "EWA", notes: "Inlander Community rack; 2 Pockets (MAX 90 BUNDLES of 30)" },
{ route: "Northeast Spokane", placeId: "ChIJN3_fgoMfnlQRHRi8ahfviXM", edition: "EWA", notes: "Inside EX Double Rack; West Door" },
{ route: "Northeast Spokane", placeId: "ChIJ38p7oYMfnlQRZiAtVSTr5lk", edition: "EWA", notes: "Front Counter" },
{ route: "Northeast Spokane", placeId: "ChIJ-SAFsWgfnlQR1_94pMZiSpc", edition: "EWA", notes: "Community top shelf to left of door" },
{ route: "Northeast Spokane", placeId: "ChIJ_2uQ5HEfnlQRY8QRYm4PF_o", edition: "EWA", notes: "Inside Single EX Rack CLOSES 2PM" },
{ route: "Northeast Spokane", placeId: "ChIJm5n2GjAfnlQRVlp2cA3RwLE", edition: "EWA", notes: "Yellow Inlander Rack" },
{ route: "Northeast Spokane", placeId: "ChIJW7XQSS4fnlQROuN69VZlH6U", edition: "EWA", notes: "Inside EX rack SOUTH door; Inside EX rack NORTH door" },
{ route: "Northeast Spokane", placeId: "ChIJMccQmtUenlQRPzEKamlcH9g", edition: "EWA", notes: "Inlander Community Rack; 1 Pocket" },
{ route: "Northeast Spokane", placeId: "ChIJhyzXUdAenlQRoMQ3dUS_tgM", edition: "EWA", notes: "Inside Community Rack Between In/Out doors" },
{ route: "Northeast Spokane", placeId: "ChIJ4WkfTdkenlQRp05r8XWPHbg", edition: "EWA", notes: "InsideEX Single Rack;" },
{ route: "Northeast Spokane", placeId: "ChIJI1nzRNwenlQRGWSWu0exdms", edition: "EWA", notes: "Inside EX Single Rack" },
{ route: "Northeast Spokane", placeId: "ChIJea0Gar8enlQRr6ximlGiFrw", edition: "EWA", notes: "Inside Yellow Inlander Rack;" },
{ route: "Northeast Spokane", placeId: "ChIJx4ojUsQfnlQRqH_n-yyCF_c", edition: "EWA", notes: "Bottom Inlander Rack" },
{ route: "Northeast Spokane", placeId: "ChIJwWGE_rAenlQRf23EHxI5c2M", edition: "EWA", notes: "Inlander Community Rack; 1 pocket" },
{ route: "Northeast Spokane", placeId: "ChIJnZ1bErAenlQRuOOHB6Xweb4", edition: "EWA", notes: "Inside EX Single Rack" },
{ route: "Northeast Spokane", placeId: "ChIJ2z2x9soenlQR9Ikm4rrb1OA", edition: "EWA", notes: "Outside EX Single Rack w/WCD" },
{ route: "Northeast Spokane", placeId: "ChIJsRssUzcZnlQRN-8bl8d7PE4", edition: "EWA", notes: "Inside Wooden community rack; 2nd Shelf" },
{ route: "Northeast Spokane", placeId: "ChIJp9pZASgZnlQRhC_KpN4e6Jg", edition: "EWA", notes: "Inside Single Exchange cream rack 3 shelves" },
{ route: "Northeast Spokane", placeId: "ChIJHd_oSdgYnlQRklUULh-oZhs", edition: "EWA", notes: "Single Exchange rack closes at 1:00 pm" },
{ route: "Northeast Spokane", placeId: "ChIJk_LaccIYnlQRh4Qa6IiR_pg", edition: "EWA", notes: "Inside Community Rack North Door" },
{ route: "Northeast Spokane", placeId: "ChIJyTdSHMIYnlQRWXZ7wQbxS90", edition: "EWA", notes: "Inlander Store rack  ; 3 Pockets; (MAX 120  bundles 30)" },
{ route: "Northeast Spokane", placeId: "ChIJITRqqrUYnlQRgsARqX3afYM", edition: "EWA", notes: "Opens 6:30am; Top of Community Rack ; Left of Door" },
{ route: "Northwest Spokane", placeId: "ChIJnbvbE_8cnlQR1amQ7SSD8Lc", edition: "EWA", notes: "Inside on waiting room table" },
{ route: "Northwest Spokane", placeId: "ChIJWfziElYcnlQR_F4umbo_5C8", edition: "EWA", notes: "Single EX rack outside w/ WCD" },
{ route: "Northwest Spokane", placeId: "ChIJhZaYalYcnlQRMewpIa-yz5g", edition: "EWA", notes: "Spokesman rack cubby between registers" },
{ route: "Northwest Spokane", placeId: "ChIJcVgQ5GocnlQRXmsuw-70da8", edition: "EWA", notes: "Open 10:30am; Inside EX Rack" },
{ route: "Northwest Spokane", placeId: "ChIJ7V3MjmocnlQRqRHdJwPDNM8", edition: "EWA", notes: "Tables" },
{ route: "Northwest Spokane", placeId: "ChIJP4PBtEAcnlQRNGjuwLFQRdo", edition: "EWA", notes: "Inside Exchange single rack" },
{ route: "Northwest Spokane", placeId: "ChIJaRjnxz8cnlQRVrk0YURzGho", edition: "EWA", notes: "Inlander Community Rack ; 2 Pockets - South Door" },
{ route: "Northwest Spokane", placeId: "ChIJJcpdzhUcnlQRz-UhDJCX_xI", edition: "EWA", notes: "Shared rack; Opens 11am" },
{ route: "Northwest Spokane", placeId: "ChIJb8Kv2j0cnlQRevHMMuXYHUw", edition: "EWA", notes: "Counter inside door to right" },
{ route: "Northwest Spokane", placeId: "ChIJmbH2jBMcnlQRLh6talscLeU", edition: "EWA", notes: "Inlander Community Rack; 1 Pocket" },
{ route: "Northwest Spokane", placeId: "ChIJ9WQ0YxQcnlQRfQSrCaiZ2Tw", edition: "EWA", notes: "Single EX rack in Foyer; AC Rack" },
{ route: "Northwest Spokane", placeId: "ChIJYX6A8A8cnlQRE-k7Kt2Dfuc", edition: "EWA", notes: "Inside Single black rack" },
{ route: "Northwest Spokane", placeId: "ChIJI1FO7qwenlQRoOL5eHnfraE", edition: "EWA", notes: "Inside Foyer EX double width double shelf Rack" },
{ route: "Northwest Spokane", placeId: "ChIJX46uugMcnlQRuHFy51tnbCI", edition: "EWA", notes: "Inside EX Single Rack" },
{ route: "Northwest Spokane", placeId: "ChIJLaYP_aoenlQRUtZCNJmAuIY", edition: "EWA", notes: "Double width EX rack; Opens 11am Max 160 (30)" },
{ route: "Northwest Spokane", placeId: "ChIJAVPYiFIZnlQR0inQyk_Wd_8", edition: "EWA", notes: "Inside EX Single Rack" },
{ route: "Northwest Spokane", placeId: "ChIJ80AAnVAZnlQRaqPjlJibLMQ", edition: "EWA", notes: "Inlander Community Rack; 1 pocket" },
{ route: "Northwest Spokane", placeId: "ChIJ4QKZQloZnlQRanRIE3vKFKw", edition: "EWA", notes: "Top basket of wine rack in foyer" },
{ route: "Northwest Spokane", placeId: "ChIJuaKTvV4ZnlQRrJ5JmkwmIxw", edition: "EWA", notes: "Top Yellow NW Rack; In window against rack" },
{ route: "Northwest Spokane", placeId: "ChIJqe3dz1gZnlQRDLjFg524vTg", edition: "EWA", notes: "Single EX Rack inside" },
{ route: "Northwest Spokane", placeId: "ChIJ9cWy5F4ZnlQRJJowzz_cnhs", edition: "EWA", notes: "Inlander Store Rack; 1 Long Pocket" },
{ route: "Northwest Spokane", placeId: "ChIJnYgLVV4ZnlQR1HHCirpXIUE", edition: "EWA", notes: "Open 10am; Use Inlander rack" },
{ route: "Northwest Spokane", placeId: "ChIJ7-HotF8ZnlQR0QTXsYgFejU", edition: "EWA", notes: "Table by chairs on left.; Opens 8am" },
{ route: "Northwest Spokane", placeId: "ChIJA9FSZtcbnlQR-91ON4g__jY", edition: "EWA", notes: "Inlander Store Rack; 1 Pocket" },
{ route: "Northwest Spokane", placeId: "ChIJO02_9K8bnlQR2FGkGU7ank4", edition: "EWA", notes: "Inlander Store Rack 1 Pocket" },
{ route: "Northwest Spokane", placeId: "ChIJaSbIGIAZnlQRNu5cNv_hCyI", edition: "EWA", notes: "Single EX rack outside NEEDS WCD" },
{ route: "Northwest Spokane", placeId: "ChIJU2qNwIUZnlQRGf3SHSVjuhE", edition: "EWA", notes: "Inside main entrance Double EX rack" },
{ route: "Northwest Spokane", placeId: "ChIJa04eImUZnlQRCRiz73LcfsM", edition: "EWA", notes: "Shared rack inside" },
{ route: "Northwest Spokane", placeId: "ChIJaezxvHMZnlQRazkyqPFG-eY", edition: "EWA", notes: "Inlander Store Rack; 1 Pocket" },
{ route: "Northwest Spokane", placeId: "ChIJQfHqOnIZnlQRyLoQgSSeh8E", edition: "EWA", notes: "Single EX rack;" },
{ route: "Northwest Spokane", placeId: "ChIJqWiKAGgZnlQRvUE1-P5GnfU", edition: "EWA", notes: "Spokesman Rack" },
{ route: "Northwest Spokane", placeId: "ChIJK5DCgrMZnlQRTP1Qc3ek1iw", edition: "EWA" },
{ route: "Northwest Spokane", placeId: "ChIJUV2gSAAZnlQRuy7HfeYA2G8", edition: "EWA" },
{ route: "Northwest Spokane", placeId: "ChIJt2pPRBsZnlQRRAYP8R13ibc", edition: "EWA", notes: "Outside Green Community Box Top Right Spot" },
{ route: "Northwest Spokane", placeId: "ChIJp71HjqQZnlQRwxuVdXAcHAs", edition: "EWA", notes: "@ Gumballs on right" },
{ route: "Northwest Spokane", placeId: "ChIJfZ1fdvgYnlQR0ZN7DJ4rzj0", edition: "EWA", notes: "Community Rack inside front door; Manager: Josh" },
{ route: "Northwest Spokane", placeId: "ChIJ9T3_UaYZnlQR9F4nrm3ZXn4", edition: "EWA", notes: "Outside EX rack" },
{ route: "Northwest Spokane", placeId: "ChIJQ6qsgQIZnlQREaF_Fn7PJP4", edition: "EWA", notes: "Top Cubby Community Rack" },
{ route: "Northwest Spokane", placeId: "ChIJG0D_PfkYnlQRMXjOnosJC0Y", edition: "EWA", notes: "Counter" },
{ route: "Northwest Spokane", placeId: "ChIJB1ZEEBsZnlQRwSGtdqOK7YE", edition: "EWA", notes: "Inside EX Rack" },
{ route: "Northwest Spokane", placeId: "ChIJ-_TJlf4YnlQRqvZtP6LxMO8", edition: "EWA", notes: "Inside Green Community Rack" },
{ route: "Northwest Spokane", placeId: "ChIJMX4V-AAZnlQRVrgPLn7yS44", edition: "EWA", notes: "Inlander Community Rack ; 2 pockets; West door MAX 100!" },
{ route: "Northwest Spokane", placeId: "ChIJLdNKcKgZnlQRYm7tQ9za3MM", edition: "EWA", notes: "Inside Inlander Rack" },
{ route: "Northwest Spokane", placeId: "ChIJVVVVVXIZnlQRRp1YvPn3Ddc", edition: "EWA", notes: "Inside Foyer" },
{ route: "Northwest Spokane", placeId: "ChIJNZfeL6IZnlQR8Ya63ifGUUo", edition: "EWA", notes: "Inside Single EX" },
{ route: "Northwest Spokane", placeId: "ChIJdXocwqkZnlQRiSKBxKUdKn0", edition: "EWA", notes: "Community Rack" },
{ route: "Northwest Spokane", placeId: "ChIJ8fvrbFUYnlQRYpu_LbxjMUA", edition: "EWA", notes: "Use bottom of Spokesman" },
{ route: "Northwest Spokane", placeId: "ChIJDyjaDFUYnlQRPEbV3bQnuis", edition: "EWA", notes: "Single EX Rack" },
{ route: "Northwest Spokane", placeId: "ChIJnTbuq1UYnlQREqo0iuf36a8", edition: "EWA", notes: "Single EX Rack" },
{ route: "Northwest Spokane", placeId: "ChIJp3Y7TVQYnlQRbz8Y0mKx0b4", edition: "EWA", notes: "Inside Single EX w/WCD" },
{ route: "Northwest Spokane", placeId: "ChIJB0BgZ0oZnlQRzz2Xrper-xA", edition: "EWA", notes: "Community rack 1 pocket" },
{ route: "Northwest Spokane", placeId: "ChIJ5yQBz1EYnlQRKwKz3ycqd9s", edition: "EWA", notes: "Gumball machine left." },
{ route: "Ritzville/ Sprague", placeId: "ChIJZYOrCADfnlQRGuvREKCm5VQ", edition: "EWA", notes: "under bottom beverage shelf" },
{ route: "Ritzville/ Sprague", placeId: "ChIJG2V4T2HenlQRn92T3Pzhp1k", edition: "EWA, WML, IND", notes: "Inside Small EX rack west end by Booths; Wenatchee/Moses Lake Exchange; 1/2 BUNDLE OF INLANDER; <-- Please write returns here" },
{ route: "Ritzville/ Sprague", placeId: "ChIJw-N05n3enlQRP4yhXuoZPk8", edition: "EWA, WML", notes: "On Shelf Right of Door" },
{ route: "Ritzville/ Sprague", placeId: "ChIJ2WQnWYbenlQROXfna9iXeDQ", edition: "EWA, WML, IND", notes: "Inlander Rack in Entry to Left; Wenatchee/Moses Lake Exchange; 1.5 BUNDLE OF INLANDER; <-- Please write returns here" },
{ route: "Ritzville/ Sprague", placeId: "ChIJF5QPGX7enlQRYu09Czb8gMM", edition: "EWA, WML", notes: "15 Max on counter; Wenatchee/Moses Lake Exchange" },
{ route: "Ritzville/ Sprague", placeId: "ChIJodBviY_enlQRgkUWcSmDQ1Q", edition: "EWA, WML", notes: "SINGLE EX RACK ENTRY; Wenatchee/Moses Lake Exchange" },
{ route: "Ritzville/ Sprague", placeId: "ChIJd-u0DzbknlQRLSOa6CLR1Vs", edition: "EWA, WML", notes: "***Tokio Weigh Station exit***(Outside rack); Wenatchee/Moses Lake Exchange" },
{ route: "Ritzville/ Sprague", placeId: "ChIJ_yi8TkD4nlQRE1R-ibwoRGk", edition: "EWA, WML", notes: "By counter at  exit door; Wenatchee/Moses Lake Exchange" },
{ route: "Ritzville/ Sprague", placeId: "ChIJGZfP_Wn4nlQRbGbkEaPIUhw", edition: "EWA, WML", notes: "Inside on counter to left; Wenatchee/Moses Lake Exchange" },
{ route: "Ritzville/ Sprague", placeId: "ChIJPR6yAWr4nlQRTnlCfRMQHnM", edition: "EWA, WML", notes: "CLOSES AT 3; Wenatchee/Moses Lake Exchange" },
{ route: "Okanagan", placeId: "ChIJl89QreptnlQRxJRMo7BG7mc", edition: "EWA, IND", notes: "1/2 BUNDLE OF INLANDER; <-- Please write returns here" },
{ route: "Okanagan", placeId: "ChIJiStGO3N7nlQRi5xDQy4VfD0", edition: "EWA" },
{ route: "Okanagan", placeId: "ChIJAeODPHN7nlQRr6C4I0AGgnU", edition: "EWA", notes: "Angle Iron Exchange Rack" },
{ route: "Okanagan", placeId: "ChIJS7LV0HZ7nlQR-JJYLrGW6Z8", edition: "EWA" },
{ route: "Okanagan", placeId: "ChIJHbPNIcIrnFQRzx0huuzdVYE", edition: "EWA", notes: "4 Shelf Exchange Rack" },
{ route: "Okanagan", placeId: "ChIJJdV0SWUvnFQRtFO0ct-6ODw", edition: "EWA", notes: "Outside Rack" },
{ route: "Okanagan", placeId: "ChIJ9X9rBnwvnFQRK6Lvzz0EgjY", edition: "EWA", notes: "In Entryway" },
{ route: "Okanagan", placeId: "ChIJ54xpdyhHnFQRKhYmSqZm3rQ", edition: "EWA, WML", notes: "Community Rack; Wenatchee Moses Lake Exchange" },
{ route: "Okanagan", placeId: "ChIJcRYiSwJHnFQRjJAa_-CDc1o", edition: "EWA", notes: "MAX 50; No Target Rack - Shelf" },
{ route: "Okanagan", placeId: "ChIJdXmCDaRHnFQRhLlNTaw2T6Q", edition: "EWA" },
{ route: "Okanagan", placeId: "ChIJidPoFHFUnFQRXiRk611S2gw", edition: "EWA", notes: "EX Angle Iron Rack; 200 Max" },
{ route: "Okanagan", placeId: "ChIJ7-_6jqvpnFQRwdaOSsqEkTU", edition: "EWA, WML", notes: "Wenatchee Moses Lake Exchange" },
{ route: "Okanagan", placeId: "ChIJbVXblvyjnFQRSKzCWbYoRNA", edition: "EWA, WML", notes: "Wenatchee Moses Lake Exchange" },
{ route: "Okanagan", placeId: "ChIJrd-mdZTrnFQRV9VdmKCMJyI", edition: "EWA, WML" },
{ route: "Okanagan", placeId: "ChIJfd7yej7rnFQRUJUFWfQMo0g", edition: "EWA, WML", notes: "Wenatchee Moses Lake Exchange" },
{ route: "Okanagan", placeId: "ChIJgyB_aqzpnFQRLBS3lCz3Rbk", edition: "EWA, WML", notes: "Wenatchee Moses Lake Exchange" },
{ route: "Okanagan", placeId: "ChIJy8kcPK3pnFQRjn7W5Sp5QlA", edition: "EWA, WML", notes: "Wenatchee Moses Lake Exchange" },
{ route: "Okanagan", placeId: "ChIJ5yIvrVDonFQRi2Q-F8VQ4FI", edition: "EWA, WML", notes: "Wenatchee Moses Lake Exchange" },
{ route: "Okanagan", placeId: "ChIJDSy_UmnonFQR3UY9Q2uYvu4", edition: "EWA, WML", notes: "Wenatchee Moses Lake Exchange" },
{ route: "Okanagan", placeId: "ChIJXT6vfOHcnFQRNYv510wKV40", edition: "EWA, WML", notes: "Wenatchee Moses Lake Exchange" },
{ route: "Okanagan", placeId: "ChIJacvDSbcpnVQRWjHysIavvZk", edition: "EWA, WML", notes: "NEEDS RACK; Wenatchee Moses Lake Exchange" },
{ route: "Okanagan", placeId: "ChIJ3_5IUropnVQR1C7SV4qASZI", edition: "EWA, WML", notes: "Wenatchee Moses Lake Exchange" },
{ route: "Okanagan", placeId: "ChIJfyR_v6QpnVQRnILUx-KZIus", edition: "EWA, WML", notes: "Wenatchee Moses Lake Exchange" },
{ route: "Okanagan", placeId: "ChIJY6j8gqQpnVQR_HHgqSKTyPc", edition: "EWA, WML", notes: "Check if open July 1; Wenatchee Moses Lake Exchange" },
{ route: "Okanagan", placeId: "ChIJLQtzfjfOglQRrcB1dsCnThI", edition: "EWA" },
{ route: "Okanagan", placeId: "ChIJ4W24TrcpnVQRvYfl-6CChvU", edition: "EWA, WML", notes: "Wenatchee Moses Lake Exchange" },
{ route: "Okanagan", placeId: "ChIJVZoWe0JqnVQRFCVRl_LRG2g", edition: "EWA" },
{ route: "Okanagan", placeId: "ChIJYTFs-UJqnVQRGvsw0veZvos", edition: "EWA" },
{ route: "Okanagan", placeId: "ChIJlRa0cMZunVQRDlH0N_3HSZI", edition: "EWA" },
{ route: "Okanagan", placeId: "ChIJ5VnG_4hpnVQRFojYb5K2EdM", edition: "EWA" },
{ route: "Palouse", placeId: "ChIJUUHbUqshnlQRNhINv4RCbYo", edition: "EWA", notes: "Outside front door, Single EX" },
{ route: "Palouse", placeId: "ChIJk-WhQBghnlQREg5Wj-DDYVg", edition: "EWA", notes: "Inlander store rack; 1 short pocket north door" },
{ route: "Palouse", placeId: "ChIJG0Xf8SIhnlQRzNGKdDkmBLA", edition: "EWA", notes: "Shared community rack" },
{ route: "Palouse", placeId: "ChIJFxJk_eclnlQRpovcf_HIHxY", edition: "EWA", notes: "Stack on Counter" },
{ route: "Palouse", placeId: "ChIJ_W_aQTopnlQRX-VHy0AHEM4", edition: "EWA", notes: "Counter" },
{ route: "Palouse", placeId: "ChIJT7C2hwcsnlQRlIQ2p6b5Ypg", edition: "EWA", notes: "Shared rack inside east door" },
{ route: "Palouse", placeId: "ChIJ60V35orPn1QRLDNatYtiaGo", edition: "EWA", notes: "Shared shelf at register" },
{ route: "Palouse", placeId: "ChIJ7VkaSo24n1QREOQ8UMftJ2I", edition: "EWA", notes: "Shared rack bottom shelf near checker" },
{ route: "Palouse", placeId: "ChIJIVDRPg6Vn1QR9DiYaqEl_eM", edition: "EWA" },
{ route: "Palouse", placeId: "ChIJA8Z4EkOSn1QRMDyQS0wZGFA", edition: "EWA", notes: "Stack on Counter" },
{ route: "Palouse", placeId: "ChIJa-UZB_mbn1QRGLdoxPnYHmk", edition: "EWA, LCV", notes: "Opens 6am; Shared rack Top Shelf; LC Valley Edition" },
{ route: "Palouse", placeId: "ChIJBWqKrP6bn1QR3XD9ZuW36xc", edition: "EWA", notes: "; Opens at 11 leave bag at door" },
{ route: "Palouse", placeId: "ChIJ5Wrqqdu1n1QRSRcMi4SdVMw", edition: "EWA, LCV", notes: "White Double EX rack by front door; LC Valley Edition" },
{ route: "Palouse", placeId: "ChIJ5f4uxNI2nlQRoWrOAJXPihM", edition: "EWA", notes: "Opens 8am; Yellow community rack in foyer" },
{ route: "Palouse", placeId: "ChIJl4trivEjnlQRDKz2XQhC5pg", edition: "EWA", notes: "Shelf at register" },
{ route: "South Hill", placeId: "ChIJNes3cwginlQR1L4juV_FG7Q", edition: "EWA", notes: "Enclosed Red Auto Clipper Rack" },
{ route: "South Hill", placeId: "ChIJz51xvl0inlQRatkJZMUsie8", edition: "EWA", notes: "Inlander Community Rack; 1 Pocket EAST ENTRANCE" },
{ route: "South Hill", placeId: "ChIJCQPw0Y0inlQRZ3KJhWtp_M0", edition: "EWA", notes: "Inlander Community Rack; 1 Pocket" },
{ route: "South Hill", placeId: "ChIJZ67J5mMjnlQRhRgfgJjtB50", edition: "EWA", notes: "Single Exchange rack by other racks" },
{ route: "South Hill", placeId: "ChIJxVuNTFwinlQRIZ9APfkpM3c", edition: "EWA", notes: "Inlander Community Rack; 1 pocket" },
{ route: "South Hill", placeId: "ChIJzV8Ll1winlQRdMYJ-ZJU44A", edition: "EWA", notes: "Inside Community Rack, opens at 10:00" },
{ route: "South Hill", placeId: "ChIJTTtptQUjnlQRqBVy5tG0bHo", edition: "EWA", notes: "Inside Community Rack" },
{ route: "South Hill", placeId: "ChIJ9dYcZd0jnlQR0FdiPxXiDkM", edition: "EWA", notes: "Exchnage Rack, inside to left 3 shelves" },
{ route: "South Hill", placeId: "ChIJo6MX51winlQRrYeOrC0qBBg", edition: "EWA", notes: "Basket on Table in Entryway" },
{ route: "South Hill", placeId: "ChIJk7v9HwQjnlQRdW9yb7cok-4", edition: "EWA", notes: "Inside EX Single Rack" },
{ route: "South Hill", placeId: "ChIJeSigZVUinlQRcC-N3KqcuIs", edition: "EWA", notes: "Inside Single Ex 2 shelves" },
{ route: "South Hill", placeId: "ChIJ8ZmkWFsinlQR_0NEIQ7uucE", edition: "EWA", notes: "waiting area" },
{ route: "Spokane Valley", placeId: "ChIJoX_mA_ofnlQRy5RkyFyoBzg", edition: "EWA", notes: "Inside EX Single Rack" },
{ route: "Spokane Valley", placeId: "ChIJ-xtPFV8fnlQRAs5TN91G3M0", edition: "EWA", notes: "Community Rack Left of entry" },
{ route: "Spokane Valley", placeId: "ChIJ7fBE7eAhnlQRNZIReAirEZ4", edition: "EWA", notes: "waiting area" },
{ route: "Spokane Valley", placeId: "ChIJ__9PNd4hnlQR9qZNL2Hl7q0", edition: "EWA", notes: "Inside Do not put on Spokesman papers" },
{ route: "Spokane Valley", placeId: "ChIJy4LKRWAhnlQRJiI3261DX8U", edition: "EWA", notes: "Single EX Rack" },
{ route: "Spokane Valley", placeId: "ChIJvXJ7I-IhnlQR9KkBN6lRf5M", edition: "EWA", notes: "SINGLE Exchange Rack at Counter" },
{ route: "Spokane Valley", placeId: "ChIJ523TscIhnlQRfjRxkQSlN3E", edition: "EWA", notes: "Shelf by register" },
{ route: "Spokane Valley", placeId: "ChIJVevdEeghnlQRYfplgRReGDA", edition: "EWA", notes: "Exchange rack in entrance" },
{ route: "Spokane Valley", placeId: "ChIJ1Zv_1zQgnlQRoImvAUwQFT4", edition: "EWA", notes: "Place in waiting area" },
{ route: "Spokane Valley", placeId: "ChIJ_S3HK8shnlQRj7p4w_oIIAU", edition: "EWA", notes: "Inside Exchange Rack CLOSES 2PM" },
{ route: "Spokane Valley", placeId: "ChIJGZSotUYgnlQR-0OyHMJ4hXA", edition: "EWA", notes: "Table by door" },
{ route: "Spokane Valley", placeId: "ChIJ6aDlEsshnlQRZ7fSD9L6qqw", edition: "EWA", notes: "Inside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJG--mDDognlQRn7R16bBuF_U", edition: "EWA", notes: "Outdoor Wood Community Rack" },
{ route: "Spokane Valley", placeId: "ChIJbaFCtUkgnlQReZAOCyF0lAM", edition: "EWA", notes: "Inside, On top of Garbage Can" },
{ route: "Spokane Valley", placeId: "ChIJ7YoW50kgnlQR3FCIxdZDPhU", edition: "EWA", notes: "Place on several tables" },
{ route: "Spokane Valley", placeId: "ChIJ0dAMakggnlQR7a8Vcc2gzNw", edition: "EWA", notes: "Inlander Community Rack; 1 Pocket + Shelf" },
{ route: "Spokane Valley", placeId: "ChIJcw3P2mkgnlQR4uTkjhk1CRA", edition: "EWA", notes: "Outside Exchange Rack Back Door" },
{ route: "Spokane Valley", placeId: "ChIJ042IEF0gnlQRHA_wmNQmN48", edition: "EWA", notes: "Outside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJWRdVrmkgnlQRLo_9RxpccP8", edition: "EWA", notes: "use space under Spokesman" },
{ route: "Spokane Valley", placeId: "ChIJsYHizWggnlQRlJQX8b2t3PQ", edition: "EWA", notes: "Inside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJlQfa53ognlQRcfN_m9536ak", edition: "EWA", notes: "On right hand side of counter" },
{ route: "Spokane Valley", placeId: "ChIJY8zq0nsgnlQRT3XerbbClg8", edition: "EWA", notes: "West side; Community Rack" },
{ route: "Spokane Valley", placeId: "ChIJAdl-QoLfYVMRk7_ZXGPQzRA", edition: "EWA", notes: "Inside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJa0olRoLfYVMRVm5tT5QQbi8", edition: "EWA", notes: "Second Shelf Community Rack" },
{ route: "Spokane Valley", placeId: "ChIJe2x3TZLfYVMREHT7DxjqoJ0", edition: "EWA", notes: "Inside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJGb8S55bfYVMR9Bx3yOiCjtU", edition: "EWA", notes: "Inside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJnTv65aLfYVMRMIrtfn-lFIk", edition: "EWA", notes: "West entrance by coffee shop" },
{ route: "Spokane Valley", placeId: "ChIJGcEwAqvfYVMRA845g21cOg8", edition: "EWA", notes: "5:30-10:30; Bag if not open; Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJRxaNCKvfYVMRN3rlODPDBNo", edition: "EWA", notes: "Exchange rack by Wendys entrance" },
{ route: "Spokane Valley", placeId: "ChIJMzv1vAbfYVMRksiXoRQge-U", edition: "EWA", notes: "Outside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJlQjp-HTfYVMRjNt5kOwy7Ds", edition: "EWA", notes: "Ziggy's rack by door" },
{ route: "Spokane Valley", placeId: "ChIJp6W_yZrfYVMR6WkaoOvz7hU", edition: "EWA", notes: "Inside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJq6ragHXfYVMRATh3qIIqNXs", edition: "EWA" },
{ route: "Spokane Valley", placeId: "ChIJQx6HMZ3fYVMRy-9NUnz5JvE", edition: "EWA", notes: "Scatter around waiting room tables" },
{ route: "Spokane Valley", placeId: "ChIJXU_wloLfYVMRBwy330jdHMg", edition: "EWA", notes: "Opens 10am; Inside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJX_qx2HUgnlQRnadsXOLLQkA", edition: "EWA", notes: "Outside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJneQslwwgnlQRGgwwuN27ajI", edition: "EWA", notes: "Inside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJNchC_WggnlQR8Z2qjp1SDF8", edition: "EWA", notes: "Inside East Door Exchange Rack   Opens at 10:30am" },
{ route: "Spokane Valley", placeId: "ChIJCQGwXFuKUocRrDLFltZDhJ8", edition: "EWA", notes: "Bottom Inlander Rack NEED RACK" },
{ route: "Spokane Valley", placeId: "ChIJf9fRC0IgnlQR58ySfEb3doE", edition: "EWA", notes: "Inside North Door; Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJE1tSHEIgnlQRY5YMkLxUK_s", edition: "EWA", notes: "Inside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJTUAogkEgnlQR9WpM_j4NLuA", edition: "EWA", notes: "One table and coffee table in waiting room" },
{ route: "Spokane Valley", placeId: "ChIJOYJNAgYhnlQRMdh3BHS94I8", edition: "EWA", notes: "Red Box outside" },
{ route: "Spokane Valley", placeId: "ChIJoffVNkIgnlQRyRuv432wqIk", edition: "EWA", notes: "on counter" },
{ route: "Spokane Valley", placeId: "ChIJezZn30cgnlQRbkFHhNGFa7Q", edition: "EWA", notes: "Round table in corner or coffee table" },
{ route: "Spokane Valley", placeId: "ChIJA2GqsMshnlQRVO05D3qSWQU", edition: "EWA", notes: "Inside Windowsill" },
{ route: "Spokane Valley", placeId: "ChIJP7f8U3EhnlQRCSTFjUadqnA", edition: "EWA" },
{ route: "Spokane Valley", placeId: "ChIJAQCQfwgcnlQRtGk1hxgIOew", edition: "EWA", notes: "Extra stop delivered when Dick stops there each week" },
{ route: "Spokane Valley", placeId: "ChIJO8sZ7xwZnlQR73rrk_xYFLU", edition: "EWA", notes: "Extra stop delivered when Dick stops there each week" },
{ route: "Spokane Valley", placeId: "ChIJxSFl-bUhnlQRo2d2U1a08sc", edition: "EWA", notes: "Extra stop delivered when Dick stops there each week" },
{ route: "Spokane Valley", placeId: "ChIJB-o2usUjnlQRRi5ywv2fmQU", edition: "EWA", notes: "Extra stop delivered when Dick stops there each week" },
{ route: "West Plains", placeId: "ChIJHWGzHlcWnlQRh2BszB0WyhI", edition: "EWA" },
{ route: "West Plains", placeId: "ChIJS9VfxS4XnlQRXI8B0WeLa-k", edition: "EWA", notes: "Opens 11 AM" },
{ route: "West Plains", placeId: "ChIJU4CVcfUWnlQRfUna5Mbl520", edition: "EWA", notes: "Wooden shelf left of door" },
{ route: "West Plains", placeId: "ChIJK9voy4gWnlQRD1sGhlXCLpM", edition: "EWA", notes: "Single EX rack by customer service counter" },
{ route: "West Plains", placeId: "ChIJ3by5GBUXnlQR1MBlbN-uwy0", edition: "EWA", notes: "Ex Rack" },
{ route: "West Plains", placeId: "ChIJg6yRHYsWnlQRQo4QAuKDdeo", edition: "EWA", notes: "EX rack w/WCD; East entrance Opens 5AM" },
{ route: "West Plains", placeId: "ChIJWXJoB4sWnlQR-G00fCLlMJY", edition: "EWA", notes: "2 white racks in Breezeway; Opens 8am" },
{ route: "West Plains", placeId: "ChIJPdz5Q4kWnlQRsMfa7kwlJso", edition: "EWA", notes: "Counter East Side of Restaurant Opens 6AM" },
{ route: "West Plains", placeId: "ChIJvc_TKYkWnlQRy4PS3X0ePPM", edition: "EWA", notes: "Rack in front of counter" },
{ route: "West Plains", placeId: "ChIJG1fjf4QWnlQRWYlMr_CIP1E", edition: "EWA", notes: "On top of Garbage/ tray return left of door OPENS 10:30" },
{ route: "West Plains", placeId: "ChIJe5RtuYUWnlQRSghXM3azy7o", edition: "EWA", notes: "Right of door on top of candy machine OPENS 11AM" },
{ route: "West Plains", placeId: "ChIJu-UwDWoUnlQRx0UG5tPjRCg", edition: "EWA", notes: "Top Shelf ; rack in cafe area" },
{ route: "West Plains", placeId: "ChIJf2H-14sWnlQRoJzZa7p6Cqs", edition: "EWA", notes: "Inside EX rack; West entrance; Opens 6AM" },
{ route: "West Plains", placeId: "ChIJk3285GIWnlQRqWdyNXmC66Y", edition: "EWA", notes: "On counter" },
{ route: "West Plains", placeId: "ChIJpT_bt1gWnlQRujUx2Rypi7I", edition: "EWA", notes: "on counter waiting area" },
{ route: "West Plains", placeId: "ChIJMTvPGVkWnlQR3rUsHDu9CVc", edition: "EWA", notes: "Opens 8am, Sinlge Ex rack" },
{ route: "West Plains", placeId: "ChIJccOB9boXnlQReuFiY2PfMPg", edition: "EWA", notes: "Inside EX Rack Front Door; Opens 11AM" },
{ route: "Spokane Valley", placeId: "ChIJR0dqMnAYnlQR13sg_m0q3bc", edition: "EWA", notes: "Inlander Community Rack; 1 Pocket 1 Shelf; WEST Entrance" },
{ route: "Spokane Valley", placeId: "ChIJlQfa53ognlQRcfN_m9536ak", edition: "EWA", notes: "On right hand side of counter" },
{ route: "Spokane Valley", placeId: "ChIJY8zq0nsgnlQRT3XerbbClg8", edition: "EWA", notes: "West side; Community Rack" },
{ route: "Spokane Valley", placeId: "ChIJT92N23sgnlQRGDHRm8PtD6I", edition: "EWA", notes: "Inlander Community Rack; 2 pockets; East Entrance" },
{ route: "Spokane Valley", placeId: "ChIJAdl-QoLfYVMRk7_ZXGPQzRA", edition: "EWA", notes: "Inside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJm0M3s4PfYVMRzDejp_VHlY4", edition: "EWA", notes: "Ex Rack" },
{ route: "Spokane Valley", placeId: "ChIJa0olRoLfYVMRVm5tT5QQbi8", edition: "EWA", notes: "Second Shelf Community Rack" },
{ route: "Spokane Valley", placeId: "ChIJe2x3TZLfYVMREHT7DxjqoJ0", edition: "EWA", notes: "Inside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJGb8S55bfYVMR9Bx3yOiCjtU", edition: "EWA", notes: "Inside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJnTv65aLfYVMRMIrtfn-lFIk", edition: "EWA", notes: "West entrance by coffee shop" },
{ route: "Spokane Valley", placeId: "ChIJGcEwAqvfYVMRA845g21cOg8", edition: "EWA", notes: "5:30-10:30; Bag if not open; Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJRxaNCKvfYVMRN3rlODPDBNo", edition: "EWA", notes: "Exchange rack by Wendys entrance" },
{ route: "Spokane Valley", placeId: "ChIJMzv1vAbfYVMRksiXoRQge-U", edition: "EWA", notes: "Outside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJlQjp-HTfYVMRjNt5kOwy7Ds", edition: "EWA", notes: "Ziggy's rack by door" },
{ route: "Spokane Valley", placeId: "ChIJp6W_yZrfYVMR6WkaoOvz7hU", edition: "EWA", notes: "Inside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJq6ragHXfYVMRATh3qIIqNXs", edition: "EWA" },
{ route: "Spokane Valley", placeId: "ChIJQx6HMZ3fYVMRy-9NUnz5JvE", edition: "EWA", notes: "Scatter around waiting room tables" },
{ route: "Spokane Valley", placeId: "ChIJXU_wloLfYVMRBwy330jdHMg", edition: "EWA", notes: "Opens 10am; Inside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJX_qx2HUgnlQRnadsXOLLQkA", edition: "EWA", notes: "Outside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJneQslwwgnlQRGgwwuN27ajI", edition: "EWA", notes: "Inside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJNchC_WggnlQR8Z2qjp1SDF8", edition: "EWA", notes: "Inside East Door Exchange Rack   Opens at 10:30am" },
{ route: "Spokane Valley", placeId: "ChIJCQGwXFuKUocRrDLFltZDhJ8", edition: "EWA", notes: "Bottom Inlander Rack NEED RACK" },
{ route: "Spokane Valley", placeId: "ChIJf9fRC0IgnlQR58ySfEb3doE", edition: "EWA", notes: "Inside North Door; Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJE1tSHEIgnlQRY5YMkLxUK_s", edition: "EWA", notes: "Inside Exchange Rack" },
{ route: "Spokane Valley", placeId: "ChIJTUAogkEgnlQR9WpM_j4NLuA", edition: "EWA", notes: "One table and coffee table in waiting room" },
{ route: "Spokane Valley", placeId: "ChIJOYJNAgYhnlQRMdh3BHS94I8", edition: "EWA", notes: "Red Box outside" },
{ route: "Spokane Valley", placeId: "ChIJoffVNkIgnlQRyRuv432wqIk", edition: "EWA", notes: "on counter" },
{ route: "Spokane Valley", placeId: "ChIJezZn30cgnlQRbkFHhNGFa7Q", edition: "EWA", notes: "Round table in corner or coffee table" },
{ route: "Spokane Valley", placeId: "ChIJA2GqsMshnlQRVO05D3qSWQU", edition: "EWA", notes: "Inside Windowsill" },
{ route: "Spokane Valley", placeId: "ChIJP7f8U3EhnlQRCSTFjUadqnA", edition: "EWA" },
{ route: "Spokane Valley", placeId: "ChIJAQCQfwgcnlQRtGk1hxgIOew", edition: "EWA", notes: "Extra stop delivered when Dick stops there each week" },
{ route: "Spokane Valley", placeId: "ChIJO8sZ7xwZnlQR73rrk_xYFLU", edition: "EWA", notes: "Extra stop delivered when Dick stops there each week" },
{ route: "Spokane Valley", placeId: "ChIJxSFl-bUhnlQRo2d2U1a08sc", edition: "EWA", notes: "Extra stop delivered when Dick stops there each week" },
{ route: "Spokane Valley", placeId: "ChIJB-o2usUjnlQRRi5ywv2fmQU", edition: "EWA", notes: "Extra stop delivered when Dick stops there each week" },
{ route: "West Plains", placeId: "ChIJHWGzHlcWnlQRh2BszB0WyhI", edition: "EWA" },
{ route: "West Plains", placeId: "ChIJS9VfxS4XnlQRXI8B0WeLa-k", edition: "EWA", notes: "Opens 11 AM" },
{ route: "West Plains", placeId: "ChIJU4CVcfUWnlQRfUna5Mbl520", edition: "EWA", notes: "Wooden shelf left of door" },
{ route: "West Plains", placeId: "ChIJK9voy4gWnlQRD1sGhlXCLpM", edition: "EWA", notes: "Single EX rack by customer service counter" },
{ route: "West Plains", placeId: "ChIJ3by5GBUXnlQR1MBlbN-uwy0", edition: "EWA", notes: "Ex Rack" },
{ route: "West Plains", placeId: "ChIJg6yRHYsWnlQRQo4QAuKDdeo", edition: "EWA", notes: "EX rack w/WCD; East entrance Opens 5AM" },
{ route: "West Plains", placeId: "ChIJWXJoB4sWnlQR-G00fCLlMJY", edition: "EWA", notes: "2 white racks in Breezeway; Opens 8am" },
{ route: "West Plains", placeId: "ChIJPdz5Q4kWnlQRsMfa7kwlJso", edition: "EWA", notes: "Counter East Side of Restaurant Opens 6AM" },
{ route: "West Plains", placeId: "ChIJvc_TKYkWnlQRy4PS3X0ePPM", edition: "EWA", notes: "Rack in front of counter" },
{ route: "West Plains", placeId: "ChIJG1fjf4QWnlQRWYlMr_CIP1E", edition: "EWA", notes: "On top of Garbage/ tray return left of door OPENS 10:30" },
{ route: "West Plains", placeId: "ChIJe5RtuYUWnlQRSghXM3azy7o", edition: "EWA", notes: "Right of door on top of candy machine OPENS 11AM" },
{ route: "West Plains", placeId: "ChIJu-UwDWoUnlQRx0UG5tPjRCg", edition: "EWA", notes: "Top Shelf ; rack in cafe area" },
{ route: "West Plains", placeId: "ChIJf2H-14sWnlQRoJzZa7p6Cqs", edition: "EWA", notes: "Inside EX rack; West entrance; Opens 6AM" },
{ route: "West Plains", placeId: "ChIJk3285GIWnlQRqWdyNXmC66Y", edition: "EWA", notes: "On counter" },
{ route: "West Plains", placeId: "ChIJpT_bt1gWnlQRujUx2Rypi7I", edition: "EWA", notes: "on counter waiting area" },
{ route: "West Plains", placeId: "ChIJMTvPGVkWnlQR3rUsHDu9CVc", edition: "EWA", notes: "Opens 8am, Sinlge Ex rack" },
{ route: "West Plains", placeId: "ChIJccOB9boXnlQReuFiY2PfMPg", edition: "EWA", notes: "Inside EX Rack Front Door; Opens 11AM" },
];